# Generated by Django 3.1.5 on 2021-02-01 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField()),
                ('short_url', models.URLField(max_length=7, unique=True)),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('max_views', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_expires', models.DateTimeField(default=datetime.datetime(2021, 2, 8, 0, 52, 25, 573268, tzinfo=utc))),
            ],
        ),
    ]
