# Generated by Django 3.1.5 on 2021-02-01 00:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 0, 53, 18, 187238, tzinfo=utc)),
        ),
    ]
