# Generated by Django 3.1.5 on 2021-01-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='password',
            new_name='key',
        ),
    ]
