# Generated by Django 3.1.5 on 2021-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_auto_20210131_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
