# Generated by Django 3.1.5 on 2021-01-31 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0003_link_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 16, 9, 28, 616005, tzinfo=utc)),
        ),
    ]
